<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="3" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Surefire suite" duration-ms="1238" started-at="2020-09-28T17:18:20 IST" finished-at="2020-09-28T17:18:21 IST">
    <groups>
    </groups>
    <test name="Surefire test" duration-ms="1238" started-at="2020-09-28T17:18:20 IST" finished-at="2020-09-28T17:18:21 IST">
      <class name="com.platform.core.TestsUser">
        <test-method status="PASS" signature="initCache()[pri:0, instance:com.platform.core.TestsUser@7dc7cbad]" name="initCache" is-config="true" duration-ms="7" started-at="2020-09-28T17:18:20 IST" finished-at="2020-09-28T17:18:20 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initCache -->
        <test-method status="FAIL" signature="TestUserCacheQuery()[pri:0, instance:com.platform.core.TestsUser@7dc7cbad]" name="TestUserCacheQuery" duration-ms="1109" started-at="2020-09-28T17:18:20 IST" finished-at="2020-09-28T17:18:21 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [id=1,name=Mukthar,age=38,gender=M] but found [id=1,name=Mukthar,age=38,gender=M,ph=]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [id=1,name=Mukthar,age=38,gender=M] but found [id=1,name=Mukthar,age=38,gender=M,ph=]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.platform.core.TestsUser.TestUserCacheQuery(TestsUser.java:84)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestUserCacheQuery -->
        <test-method status="PASS" signature="TestUserChangingSchema()[pri:0, instance:com.platform.core.TestsUser@7dc7cbad]" name="TestUserChangingSchema" duration-ms="22" started-at="2020-09-28T17:18:21 IST" finished-at="2020-09-28T17:18:21 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestUserChangingSchema -->
        <test-method status="FAIL" signature="TestUserRegistration()[pri:0, instance:com.platform.core.TestsUser@7dc7cbad]" name="TestUserRegistration" duration-ms="9" started-at="2020-09-28T17:18:21 IST" finished-at="2020-09-28T17:18:21 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [id=1,name=Mukthar,age=38,gender=M] but found [id=1,name=Mukthar,age=38,gender=M,ph=]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [id=1,name=Mukthar,age=38,gender=M] but found [id=1,name=Mukthar,age=38,gender=M,ph=]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at com.platform.core.TestsUser.TestUserRegistration(TestsUser.java:44)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:373)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:334)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:407)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestUserRegistration -->
        <test-method status="PASS" signature="killCache()[pri:0, instance:com.platform.core.TestsUser@7dc7cbad]" name="killCache" is-config="true" duration-ms="37" started-at="2020-09-28T17:18:21 IST" finished-at="2020-09-28T17:18:21 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- killCache -->
      </class> <!-- com.platform.core.TestsUser -->
    </test> <!-- Surefire test -->
  </suite> <!-- Surefire suite -->
</testng-results>
